// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Ods
{

    // Agency
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AgencyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Agency>
    {
        public AgencyConfiguration()
            : this("dbo")
        {
        }

        public AgencyConfiguration(string schema)
        {
            ToTable("Agency", schema);
            HasKey(x => new { x.EducationOrganizationId, x.NameOfInstitution, x.IsChoice, x.SchoolYear });

            Property(x => x.EducationOrganizationId).HasColumnName(@"EducationOrganizationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NameOfInstitution).HasColumnName(@"NameOfInstitution").HasColumnType("nvarchar").IsRequired().HasMaxLength(75).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsChoice).HasColumnName(@"IsChoice").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AgencyCode).HasColumnName(@"AgencyCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(60);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.SchoolYear).HasColumnName(@"SchoolYear").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AgencyType).HasColumnName(@"AgencyType").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.AgencyTypeDescription).HasColumnName(@"AgencyTypeDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
