// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Ods
{

    // Agency
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class Agency
    {
        public int EducationOrganizationId { get; set; } // EducationOrganizationId (Primary key)
        public string NameOfInstitution { get; set; } // NameOfInstitution (Primary key) (length: 75)
        public bool IsChoice { get; set; } // IsChoice (Primary key)
        public string AgencyCode { get; set; } // AgencyCode (length: 60)
        public string City { get; set; } // City (length: 30)
        public short SchoolYear { get; set; } // SchoolYear (Primary key)
        public string AgencyType { get; set; } // AgencyType (length: 50)
        public string AgencyTypeDescription { get; set; } // AgencyTypeDescription (length: 1024)

        public Agency()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
