// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Ods
{

    // AgencySchool
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AgencySchool
    {
        public int EducationOrganizationId { get; set; } // EducationOrganizationId (Primary key)
        public int LocalEducationAgencyId { get; set; } // LocalEducationAgencyId (Primary key)
        public string NameOfInstitution { get; set; } // NameOfInstitution (Primary key) (length: 75)
        public bool IsChoice { get; set; } // IsChoice (Primary key)
        public string SchoolCode { get; set; } // SchoolCode (length: 60)
        public string City { get; set; } // City (length: 30)
        public short SchoolYear { get; set; } // SchoolYear (Primary key)
        public string SchoolAgencyType { get; set; } // SchoolAgencyType (length: 50)
        public int SchoolType { get; set; } // SchoolType (Primary key)
        public string SchoolTypeDescription { get; set; } // SchoolTypeDescription (Primary key) (length: 1024)
        public string SchoolTypeCode { get; set; } // SchoolTypeCode (Primary key) (length: 50)

        public AgencySchool()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
