// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // Actions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class Action
    {
        public int ActionId { get; set; } // ActionId (Primary key)
        public string ActionName { get; set; } // ActionName (length: 255)
        public string ActionUri { get; set; } // ActionUri (length: 2048)

        // Reverse navigation

        /// <summary>
        /// Child ClaimSetResourceClaims where [ClaimSetResourceClaims].[Action_ActionId] point to this entity (FK_dbo.ClaimSetResourceClaims_dbo.Actions_Action_ActionId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClaimSetResourceClaim> ClaimSetResourceClaims { get; set; } // ClaimSetResourceClaims.FK_dbo.ClaimSetResourceClaims_dbo.Actions_Action_ActionId

        public Action()
        {
            ClaimSetResourceClaims = new System.Collections.Generic.List<ClaimSetResourceClaim>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
