// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // AllowedActionsByClaimset
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AllowedActionsByClaimset
    {
        public string ResourceName { get; set; } // ResourceName (Primary key) (length: 2048)
        public string ActionName { get; set; } // ActionName (Primary key) (length: 255)
        public string ClaimSetName { get; set; } // ClaimSetName (Primary key) (length: 255)

        public AllowedActionsByClaimset()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
