// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // AllowedActionsByClaimset
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AllowedActionsByClaimsetConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AllowedActionsByClaimset>
    {
        public AllowedActionsByClaimsetConfiguration()
            : this("dbo")
        {
        }

        public AllowedActionsByClaimsetConfiguration(string schema)
        {
            ToTable("AllowedActionsByClaimset", schema);
            HasKey(x => new { x.ResourceName, x.ActionName, x.ClaimSetName });

            Property(x => x.ResourceName).HasColumnName(@"ResourceName").HasColumnType("nvarchar").IsRequired().HasMaxLength(2048).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ActionName).HasColumnName(@"ActionName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ClaimSetName).HasColumnName(@"ClaimSetName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
