// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ApiClients
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ApiClient
    {
        public int ApiClientId { get; set; } // ApiClientId (Primary key)
        public string Key { get; set; } // Key (length: 50)
        public string Secret { get; set; } // Secret (length: 100)
        public string Name { get; set; } // Name (length: 50)
        public bool IsApproved { get; set; } // IsApproved
        public bool UseSandbox { get; set; } // UseSandbox
        public int SandboxType { get; set; } // SandboxType
        public int? ApplicationApplicationId { get; set; } // Application_ApplicationId
        public int? UserUserId { get; set; } // User_UserId
        public string KeyStatus { get; set; } // KeyStatus
        public string ChallengeId { get; set; } // ChallengeId
        public System.DateTime? ChallengeExpiry { get; set; } // ChallengeExpiry
        public string ActivationCode { get; set; } // ActivationCode
        public int? ActivationRetried { get; set; } // ActivationRetried
        public bool SecretIsHashed { get; set; } // SecretIsHashed
        public string StudentIdentificationSystemDescriptor { get; set; } // StudentIdentificationSystemDescriptor (length: 306)

        // Reverse navigation

        /// <summary>
        /// Child ApplicationEducationOrganizations (Many-to-Many) mapped by table [ApiClientApplicationEducationOrganizations]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApplicationEducationOrganization> ApplicationEducationOrganizations { get; set; } // Many to many mapping
        /// <summary>
        /// Child ClientAccessTokens where [ClientAccessTokens].[ApiClient_ApiClientId] point to this entity (FK_dbo.ClientAccessTokens_dbo.ApiClients_ApiClient_ApiClientId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClientAccessToken> ClientAccessTokens { get; set; } // ClientAccessTokens.FK_dbo.ClientAccessTokens_dbo.ApiClients_ApiClient_ApiClientId

        // Foreign keys

        /// <summary>
        /// Parent Application pointed by [ApiClients].([ApplicationApplicationId]) (FK_dbo.ApiClients_dbo.Applications_Application_ApplicationId)
        /// </summary>
        public virtual Application Application { get; set; } // FK_dbo.ApiClients_dbo.Applications_Application_ApplicationId

        /// <summary>
        /// Parent User pointed by [ApiClients].([UserUserId]) (FK_dbo.ApiClients_dbo.Users_User_UserId)
        /// </summary>
        public virtual User User { get; set; } // FK_dbo.ApiClients_dbo.Users_User_UserId

        public ApiClient()
        {
            SecretIsHashed = false;
            ClientAccessTokens = new System.Collections.Generic.List<ClientAccessToken>();
            ApplicationEducationOrganizations = new System.Collections.Generic.List<ApplicationEducationOrganization>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
