// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // Applications
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class Application
    {
        public int ApplicationId { get; set; } // ApplicationId (Primary key)
        public string ApplicationName { get; set; } // ApplicationName
        public int? VendorVendorId { get; set; } // Vendor_VendorId
        public string ClaimSetName { get; set; } // ClaimSetName (length: 255)
        public int? OdsInstanceOdsInstanceId { get; set; } // OdsInstance_OdsInstanceId
        public string OperationalContextUri { get; set; } // OperationalContextUri (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child ApiClients where [ApiClients].[Application_ApplicationId] point to this entity (FK_dbo.ApiClients_dbo.Applications_Application_ApplicationId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApiClient> ApiClients { get; set; } // ApiClients.FK_dbo.ApiClients_dbo.Applications_Application_ApplicationId
        /// <summary>
        /// Child ApplicationEducationOrganizations where [ApplicationEducationOrganizations].[Application_ApplicationId] point to this entity (FK_dbo.ApplicationEducationOrganizations_dbo.Applications_Application_ApplicationId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApplicationEducationOrganization> ApplicationEducationOrganizations { get; set; } // ApplicationEducationOrganizations.FK_dbo.ApplicationEducationOrganizations_dbo.Applications_Application_ApplicationId
        /// <summary>
        /// Child Profiles (Many-to-Many) mapped by table [ProfileApplications]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Profile> Profiles { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Vendor pointed by [Applications].([VendorVendorId]) (FK_dbo.Applications_dbo.Vendors_Vendor_VendorId)
        /// </summary>
        public virtual Vendor Vendor { get; set; } // FK_dbo.Applications_dbo.Vendors_Vendor_VendorId

        public Application()
        {
            OperationalContextUri = "";
            ApiClients = new System.Collections.Generic.List<ApiClient>();
            ApplicationEducationOrganizations = new System.Collections.Generic.List<ApplicationEducationOrganization>();
            Profiles = new System.Collections.Generic.List<Profile>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
