// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ApplicationEducationOrganizations
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ApplicationEducationOrganizationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApplicationEducationOrganization>
    {
        public ApplicationEducationOrganizationConfiguration()
            : this("dbo")
        {
        }

        public ApplicationEducationOrganizationConfiguration(string schema)
        {
            ToTable("ApplicationEducationOrganizations", schema);
            HasKey(x => x.ApplicationEducationOrganizationId);

            Property(x => x.ApplicationEducationOrganizationId).HasColumnName(@"ApplicationEducationOrganizationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EducationOrganizationId).HasColumnName(@"EducationOrganizationId").HasColumnType("int").IsRequired();
            Property(x => x.ApplicationApplicationId).HasColumnName(@"Application_ApplicationId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Application).WithMany(b => b.ApplicationEducationOrganizations).HasForeignKey(c => c.ApplicationApplicationId).WillCascadeOnDelete(false); // FK_dbo.ApplicationEducationOrganizations_dbo.Applications_Application_ApplicationId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
