// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ApplicationEducationOrganizations
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ApplicationEducationOrganization
    {
        public int ApplicationEducationOrganizationId { get; set; } // ApplicationEducationOrganizationId (Primary key)
        public int EducationOrganizationId { get; set; } // EducationOrganizationId
        public int? ApplicationApplicationId { get; set; } // Application_ApplicationId

        // Reverse navigation

        /// <summary>
        /// Child ApiClients (Many-to-Many) mapped by table [ApiClientApplicationEducationOrganizations]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApiClient> ApiClients { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Application pointed by [ApplicationEducationOrganizations].([ApplicationApplicationId]) (FK_dbo.ApplicationEducationOrganizations_dbo.Applications_Application_ApplicationId)
        /// </summary>
        public virtual Application Application { get; set; } // FK_dbo.ApplicationEducationOrganizations_dbo.Applications_Application_ApplicationId

        public ApplicationEducationOrganization()
        {
            ApiClients = new System.Collections.Generic.List<ApiClient>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
