// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // AuditEntryProperty
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AuditEntryProperty
    {
        public int AuditEntryPropertyId { get; set; } // AuditEntryPropertyId (Primary key)
        public int AuditEntryId { get; set; } // AuditEntryId
        public string PropertyName { get; set; } // PropertyName (length: 255)
        public string OldValue { get; set; } // OldValue
        public string NewValue { get; set; } // NewValue

        // Foreign keys

        /// <summary>
        /// Parent AuditEntry pointed by [AuditEntryProperty].([AuditEntryId]) (FK_AuditEntryProperty_AuditEntry_AuditEntryId)
        /// </summary>
        public virtual AuditEntry AuditEntry { get; set; } // FK_AuditEntryProperty_AuditEntry_AuditEntryId

        public AuditEntryProperty()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
