// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // AuditEntry
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AuditEntry
    {
        public int AuditEntryId { get; set; } // AuditEntryId (Primary key)
        public string EntityTypeName { get; set; } // EntityTypeName (length: 255)
        public int State { get; set; } // State
        public string StateName { get; set; } // StateName (length: 255)
        public string CreatedBy { get; set; } // CreatedBy (length: 255)
        public System.DateTime CreatedDate { get; set; } // CreatedDate

        // Reverse navigation

        /// <summary>
        /// Child AuditEntryProperties where [AuditEntryProperty].[AuditEntryId] point to this entity (FK_AuditEntryProperty_AuditEntry_AuditEntryId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AuditEntryProperty> AuditEntryProperties { get; set; } // AuditEntryProperty.FK_AuditEntryProperty_AuditEntry_AuditEntryId

        public AuditEntry()
        {
            AuditEntryProperties = new System.Collections.Generic.List<AuditEntryProperty>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
