// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // AuditEntryProperty
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AuditEntryPropertyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AuditEntryProperty>
    {
        public AuditEntryPropertyConfiguration()
            : this("dbo")
        {
        }

        public AuditEntryPropertyConfiguration(string schema)
        {
            ToTable("AuditEntryProperty", schema);
            HasKey(x => x.AuditEntryPropertyId);

            Property(x => x.AuditEntryPropertyId).HasColumnName(@"AuditEntryPropertyId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AuditEntryId).HasColumnName(@"AuditEntryId").HasColumnType("int").IsRequired();
            Property(x => x.PropertyName).HasColumnName(@"PropertyName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.OldValue).HasColumnName(@"OldValue").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.NewValue).HasColumnName(@"NewValue").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.AuditEntry).WithMany(b => b.AuditEntryProperties).HasForeignKey(c => c.AuditEntryId); // FK_AuditEntryProperty_AuditEntry_AuditEntryId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
