// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // AuthorizationStrategies
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class AuthorizationStrategyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AuthorizationStrategy>
    {
        public AuthorizationStrategyConfiguration()
            : this("dbo")
        {
        }

        public AuthorizationStrategyConfiguration(string schema)
        {
            ToTable("AuthorizationStrategies", schema);
            HasKey(x => x.AuthorizationStrategyId);

            Property(x => x.AuthorizationStrategyId).HasColumnName(@"AuthorizationStrategyId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.AuthorizationStrategyName).HasColumnName(@"AuthorizationStrategyName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.ApplicationApplicationId).HasColumnName(@"Application_ApplicationId").HasColumnType("int").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
