// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ClaimSets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ClaimSetConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClaimSet>
    {
        public ClaimSetConfiguration()
            : this("dbo")
        {
        }

        public ClaimSetConfiguration(string schema)
        {
            ToTable("ClaimSets", schema);
            HasKey(x => x.ClaimSetId);

            Property(x => x.ClaimSetId).HasColumnName(@"ClaimSetId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClaimSetName).HasColumnName(@"ClaimSetName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.ApplicationApplicationId).HasColumnName(@"Application_ApplicationId").HasColumnType("int").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
