// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ClaimSetResourceClaims
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ClaimSetResourceClaim
    {
        public int ClaimSetResourceClaimId { get; set; } // ClaimSetResourceClaimId (Primary key)
        public int ActionActionId { get; set; } // Action_ActionId
        public int ClaimSetClaimSetId { get; set; } // ClaimSet_ClaimSetId
        public int ResourceClaimResourceClaimId { get; set; } // ResourceClaim_ResourceClaimId
        public int? AuthorizationStrategyOverrideAuthorizationStrategyId { get; set; } // AuthorizationStrategyOverride_AuthorizationStrategyId
        public string ValidationRuleSetNameOverride { get; set; } // ValidationRuleSetNameOverride (length: 255)

        // Foreign keys

        /// <summary>
        /// Parent Action pointed by [ClaimSetResourceClaims].([ActionActionId]) (FK_dbo.ClaimSetResourceClaims_dbo.Actions_Action_ActionId)
        /// </summary>
        public virtual Action Action { get; set; } // FK_dbo.ClaimSetResourceClaims_dbo.Actions_Action_ActionId

        /// <summary>
        /// Parent AuthorizationStrategy pointed by [ClaimSetResourceClaims].([AuthorizationStrategyOverrideAuthorizationStrategyId]) (FK_dbo.ClaimSetResourceClaims_dbo.AuthorizationStrategies_AuthorizationStrategyOverride_AuthorizationStrategyId)
        /// </summary>
        public virtual AuthorizationStrategy AuthorizationStrategy { get; set; } // FK_dbo.ClaimSetResourceClaims_dbo.AuthorizationStrategies_AuthorizationStrategyOverride_AuthorizationStrategyId

        /// <summary>
        /// Parent ClaimSet pointed by [ClaimSetResourceClaims].([ClaimSetClaimSetId]) (FK_dbo.ClaimSetResourceClaims_dbo.ClaimSets_ClaimSet_ClaimSetId)
        /// </summary>
        public virtual ClaimSet ClaimSet { get; set; } // FK_dbo.ClaimSetResourceClaims_dbo.ClaimSets_ClaimSet_ClaimSetId

        /// <summary>
        /// Parent ResourceClaim pointed by [ClaimSetResourceClaims].([ResourceClaimResourceClaimId]) (FK_dbo.ClaimSetResourceClaims_dbo.ResourceClaims_ResourceClaim_ResourceClaimId)
        /// </summary>
        public virtual ResourceClaim ResourceClaim { get; set; } // FK_dbo.ClaimSetResourceClaims_dbo.ResourceClaims_ResourceClaim_ResourceClaimId

        public ClaimSetResourceClaim()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
