// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ClaimsetDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ClaimsetDetail
    {
        public string ClaimSetName { get; set; } // ClaimSetName (Primary key) (length: 255)
        public string PlainEnglish { get; set; } // PlainEnglish (length: 1000)
        public string LogicalDomain { get; set; } // LogicalDomain (length: 100)
        public bool PrimarySis { get; set; } // PrimarySis
        public bool PublicClaimset { get; set; } // PublicClaimset
        public bool ChoiceClaimset { get; set; } // ChoiceClaimset
        public bool SchoolLevelClaimset { get; set; } // SchoolLevelClaimset
        public bool ReadOnlyClaimset { get; set; } // ReadOnlyClaimset
        public bool Active { get; set; } // Active
        public int? RequirementYear { get; set; } // RequirementYear
        public int? ProfileId { get; set; } // ProfileId
        public int? ClaimsetTypeId { get; set; } // ClaimsetTypeId

        // Foreign keys

        /// <summary>
        /// Parent ClaimsetType pointed by [ClaimsetDetails].([ClaimsetTypeId]) (FK_ClaimsetDetail_ClaimsetType)
        /// </summary>
        public virtual ClaimsetType ClaimsetType { get; set; } // FK_ClaimsetDetail_ClaimsetType

        /// <summary>
        /// Parent Profile pointed by [ClaimsetDetails].([ProfileId]) (FK_ClaimsetDetail_Profile)
        /// </summary>
        public virtual Profile Profile { get; set; } // FK_ClaimsetDetail_Profile

        public ClaimsetDetail()
        {
            PrimarySis = false;
            PublicClaimset = false;
            ChoiceClaimset = false;
            SchoolLevelClaimset = false;
            ReadOnlyClaimset = false;
            Active = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
