// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ClaimSets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ClaimSet
    {
        public int ClaimSetId { get; set; } // ClaimSetId (Primary key)
        public string ClaimSetName { get; set; } // ClaimSetName (length: 255)
        public int ApplicationApplicationId { get; set; } // Application_ApplicationId

        // Reverse navigation

        /// <summary>
        /// Child ClaimSetResourceClaims where [ClaimSetResourceClaims].[ClaimSet_ClaimSetId] point to this entity (FK_dbo.ClaimSetResourceClaims_dbo.ClaimSets_ClaimSet_ClaimSetId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClaimSetResourceClaim> ClaimSetResourceClaims { get; set; } // ClaimSetResourceClaims.FK_dbo.ClaimSetResourceClaims_dbo.ClaimSets_ClaimSet_ClaimSetId

        public ClaimSet()
        {
            ClaimSetResourceClaims = new System.Collections.Generic.List<ClaimSetResourceClaim>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
