// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ClaimsetType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ClaimsetType
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 200)

        // Reverse navigation

        /// <summary>
        /// Child ClaimsetDetails where [ClaimsetDetails].[ClaimsetTypeId] point to this entity (FK_ClaimsetDetail_ClaimsetType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClaimsetDetail> ClaimsetDetails { get; set; } // ClaimsetDetails.FK_ClaimsetDetail_ClaimsetType

        public ClaimsetType()
        {
            ClaimsetDetails = new System.Collections.Generic.List<ClaimsetDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
