// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ClientAccessTokens
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ClientAccessToken
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.DateTime Expiration { get; set; } // Expiration
        public string Scope { get; set; } // Scope
        public int? ApiClientApiClientId { get; set; } // ApiClient_ApiClientId

        // Foreign keys

        /// <summary>
        /// Parent ApiClient pointed by [ClientAccessTokens].([ApiClientApiClientId]) (FK_dbo.ClientAccessTokens_dbo.ApiClients_ApiClient_ApiClientId)
        /// </summary>
        public virtual ApiClient ApiClient { get; set; } // FK_dbo.ClientAccessTokens_dbo.ApiClients_ApiClient_ApiClientId

        public ClientAccessToken()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
