// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // Crosstab
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class Crosstab
    {
        public string RowId { get; set; } // RowId (Primary key) (length: 25)
        public int ApiClientId { get; set; } // ApiClientId (Primary key)
        public int? SchoolId { get; set; } // SchoolId
        public string SchoolName { get; set; } // SchoolName (length: 75)
        public int? LeaId { get; set; } // LeaId
        public string LeaName { get; set; } // LeaName (length: 75)
        public string VendorName { get; set; } // VendorName
        public string ApiClientName { get; set; } // ApiClientName (Primary key) (length: 50)
        public string ApiKey { get; set; } // ApiKey (Primary key) (length: 50)
        public string Secret { get; set; } // Secret (Primary key) (length: 100)
        public string ClaimSetName { get; set; } // ClaimSetName (length: 255)
        public string ProfileName { get; set; } // ProfileName

        public Crosstab()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
