// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class EdFiAdminDbContext : System.Data.Entity.DbContext, IEdFiAdminDbContextBase
    {
        public System.Data.Entity.DbSet<Agreement> Agreements { get; set; } // Agreement
        public System.Data.Entity.DbSet<ApiClient> ApiClients { get; set; } // ApiClients
        public System.Data.Entity.DbSet<Application> Applications { get; set; } // Applications
        public System.Data.Entity.DbSet<ApplicationEducationOrganization> ApplicationEducationOrganizations { get; set; } // ApplicationEducationOrganizations
        public System.Data.Entity.DbSet<AsmUser> AsmUsers { get; set; } // AsmUser
        public System.Data.Entity.DbSet<AuditEntry> AuditEntries { get; set; } // AuditEntry
        public System.Data.Entity.DbSet<AuditEntryProperty> AuditEntryProperties { get; set; } // AuditEntryProperty
        public System.Data.Entity.DbSet<ClaimsetDetail> ClaimsetDetails { get; set; } // ClaimsetDetails
        public System.Data.Entity.DbSet<ClaimsetType> ClaimsetTypes { get; set; } // ClaimsetType
        public System.Data.Entity.DbSet<ClientAccessToken> ClientAccessTokens { get; set; } // ClientAccessTokens
        public System.Data.Entity.DbSet<Crosstab> Crosstabs { get; set; } // Crosstab
        public System.Data.Entity.DbSet<LatestEdOrg> LatestEdOrgs { get; set; } // LatestEdOrgs
        public System.Data.Entity.DbSet<Lookup> Lookups { get; set; } // Lookup
        public System.Data.Entity.DbSet<Profile> Profiles { get; set; } // Profiles
        public System.Data.Entity.DbSet<SiteContent> SiteContents { get; set; } // SiteContent
        public System.Data.Entity.DbSet<Subscription> Subscriptions { get; set; } // Subscription
        public System.Data.Entity.DbSet<SubscriptionAction> SubscriptionActions { get; set; } // SubscriptionAction
        public System.Data.Entity.DbSet<User> Users { get; set; } // Users
        public System.Data.Entity.DbSet<UserAsmUser> UserAsmUsers { get; set; } // UserAsmUser
        public System.Data.Entity.DbSet<Vendor> Vendors { get; set; } // Vendors
        public System.Data.Entity.DbSet<VendorEmailDomain> VendorEmailDomains { get; set; } // VendorEmailDomains
        public System.Data.Entity.DbSet<VendorNamespacePrefix> VendorNamespacePrefixes { get; set; } // VendorNamespacePrefixes

        static EdFiAdminDbContext()
        {
            System.Data.Entity.Database.SetInitializer<EdFiAdminDbContext>(null);
        }

        public EdFiAdminDbContext()
            : base("Name=EdFiAdminDbContext")
        {
            InitializePartial();
        }

        public EdFiAdminDbContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }

        public EdFiAdminDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public EdFiAdminDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public EdFiAdminDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AgreementConfiguration());
            modelBuilder.Configurations.Add(new ApiClientConfiguration());
            modelBuilder.Configurations.Add(new ApplicationConfiguration());
            modelBuilder.Configurations.Add(new ApplicationEducationOrganizationConfiguration());
            modelBuilder.Configurations.Add(new AsmUserConfiguration());
            modelBuilder.Configurations.Add(new AuditEntryConfiguration());
            modelBuilder.Configurations.Add(new AuditEntryPropertyConfiguration());
            modelBuilder.Configurations.Add(new ClaimsetDetailConfiguration());
            modelBuilder.Configurations.Add(new ClaimsetTypeConfiguration());
            modelBuilder.Configurations.Add(new ClientAccessTokenConfiguration());
            modelBuilder.Configurations.Add(new CrosstabConfiguration());
            modelBuilder.Configurations.Add(new LatestEdOrgConfiguration());
            modelBuilder.Configurations.Add(new LookupConfiguration());
            modelBuilder.Configurations.Add(new ProfileConfiguration());
            modelBuilder.Configurations.Add(new SiteContentConfiguration());
            modelBuilder.Configurations.Add(new SubscriptionConfiguration());
            modelBuilder.Configurations.Add(new SubscriptionActionConfiguration());
            modelBuilder.Configurations.Add(new UserConfiguration());
            modelBuilder.Configurations.Add(new UserAsmUserConfiguration());
            modelBuilder.Configurations.Add(new VendorConfiguration());
            modelBuilder.Configurations.Add(new VendorEmailDomainConfiguration());
            modelBuilder.Configurations.Add(new VendorNamespacePrefixConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AgreementConfiguration(schema));
            modelBuilder.Configurations.Add(new ApiClientConfiguration(schema));
            modelBuilder.Configurations.Add(new ApplicationConfiguration(schema));
            modelBuilder.Configurations.Add(new ApplicationEducationOrganizationConfiguration(schema));
            modelBuilder.Configurations.Add(new AsmUserConfiguration(schema));
            modelBuilder.Configurations.Add(new AuditEntryConfiguration(schema));
            modelBuilder.Configurations.Add(new AuditEntryPropertyConfiguration(schema));
            modelBuilder.Configurations.Add(new ClaimsetDetailConfiguration(schema));
            modelBuilder.Configurations.Add(new ClaimsetTypeConfiguration(schema));
            modelBuilder.Configurations.Add(new ClientAccessTokenConfiguration(schema));
            modelBuilder.Configurations.Add(new CrosstabConfiguration(schema));
            modelBuilder.Configurations.Add(new LatestEdOrgConfiguration(schema));
            modelBuilder.Configurations.Add(new LookupConfiguration(schema));
            modelBuilder.Configurations.Add(new ProfileConfiguration(schema));
            modelBuilder.Configurations.Add(new SiteContentConfiguration(schema));
            modelBuilder.Configurations.Add(new SubscriptionConfiguration(schema));
            modelBuilder.Configurations.Add(new SubscriptionActionConfiguration(schema));
            modelBuilder.Configurations.Add(new UserConfiguration(schema));
            modelBuilder.Configurations.Add(new UserAsmUserConfiguration(schema));
            modelBuilder.Configurations.Add(new VendorConfiguration(schema));
            modelBuilder.Configurations.Add(new VendorEmailDomainConfiguration(schema));
            modelBuilder.Configurations.Add(new VendorNamespacePrefixConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
}
// </auto-generated>
