// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class EdFiSecurityDbContext : System.Data.Entity.DbContext, IEdFiSecurityDbContextBase
    {
        public System.Data.Entity.DbSet<Action> Actions { get; set; } // Actions
        public System.Data.Entity.DbSet<AllowedActionsByClaimset> AllowedActionsByClaimsets { get; set; } // AllowedActionsByClaimset
        public System.Data.Entity.DbSet<AuthorizationStrategy> AuthorizationStrategies { get; set; } // AuthorizationStrategies
        public System.Data.Entity.DbSet<ClaimSet> ClaimSets { get; set; } // ClaimSets
        public System.Data.Entity.DbSet<ClaimSetResourceClaim> ClaimSetResourceClaims { get; set; } // ClaimSetResourceClaims
        public System.Data.Entity.DbSet<ResourceClaim> ResourceClaims { get; set; } // ResourceClaims
        public System.Data.Entity.DbSet<SecurityStrategy> SecurityStrategies { get; set; } // SecurityStrategies

        static EdFiSecurityDbContext()
        {
            System.Data.Entity.Database.SetInitializer<EdFiSecurityDbContext>(null);
        }

        public EdFiSecurityDbContext()
            : base("Name=EdFiSecurityDbContext")
        {
            InitializePartial();
        }

        public EdFiSecurityDbContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }

        public EdFiSecurityDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public EdFiSecurityDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public EdFiSecurityDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new ActionConfiguration());
            modelBuilder.Configurations.Add(new AllowedActionsByClaimsetConfiguration());
            modelBuilder.Configurations.Add(new AuthorizationStrategyConfiguration());
            modelBuilder.Configurations.Add(new ClaimSetConfiguration());
            modelBuilder.Configurations.Add(new ClaimSetResourceClaimConfiguration());
            modelBuilder.Configurations.Add(new ResourceClaimConfiguration());
            modelBuilder.Configurations.Add(new SecurityStrategyConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new ActionConfiguration(schema));
            modelBuilder.Configurations.Add(new AllowedActionsByClaimsetConfiguration(schema));
            modelBuilder.Configurations.Add(new AuthorizationStrategyConfiguration(schema));
            modelBuilder.Configurations.Add(new ClaimSetConfiguration(schema));
            modelBuilder.Configurations.Add(new ClaimSetResourceClaimConfiguration(schema));
            modelBuilder.Configurations.Add(new ResourceClaimConfiguration(schema));
            modelBuilder.Configurations.Add(new SecurityStrategyConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
}
// </auto-generated>
