// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // LatestEdOrgs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class LatestEdOrg
    {
        public int EducationOrganizationId { get; set; } // EducationOrganizationId (Primary key)
        public short? SchoolYear { get; set; } // SchoolYear
        public string NameOfInstitution { get; set; } // NameOfInstitution (length: 75)
        public int? LocalEducationAgencyId { get; set; } // LocalEducationAgencyId
        public string Lea { get; set; } // Lea (length: 75)
        public string City { get; set; } // City (length: 30)

        public LatestEdOrg()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
