// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // LatestEdOrgs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class LatestEdOrgConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LatestEdOrg>
    {
        public LatestEdOrgConfiguration()
            : this("dbo")
        {
        }

        public LatestEdOrgConfiguration(string schema)
        {
            ToTable("LatestEdOrgs", schema);
            HasKey(x => x.EducationOrganizationId);

            Property(x => x.EducationOrganizationId).HasColumnName(@"EducationOrganizationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolYear).HasColumnName(@"SchoolYear").HasColumnType("smallint").IsOptional();
            Property(x => x.NameOfInstitution).HasColumnName(@"NameOfInstitution").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.LocalEducationAgencyId).HasColumnName(@"LocalEducationAgencyId").HasColumnType("int").IsOptional();
            Property(x => x.Lea).HasColumnName(@"Lea").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
