// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // Profiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class Profile
    {
        public int ProfileId { get; set; } // ProfileId (Primary key)
        public string ProfileName { get; set; } // ProfileName

        // Reverse navigation

        /// <summary>
        /// Child Applications (Many-to-Many) mapped by table [ProfileApplications]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Application> Applications { get; set; } // Many to many mapping
        /// <summary>
        /// Child ClaimsetDetails where [ClaimsetDetails].[ProfileId] point to this entity (FK_ClaimsetDetail_Profile)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClaimsetDetail> ClaimsetDetails { get; set; } // ClaimsetDetails.FK_ClaimsetDetail_Profile

        public Profile()
        {
            ClaimsetDetails = new System.Collections.Generic.List<ClaimsetDetail>();
            Applications = new System.Collections.Generic.List<Application>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
