// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // ResourceClaims
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ResourceClaimConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ResourceClaim>
    {
        public ResourceClaimConfiguration()
            : this("dbo")
        {
        }

        public ResourceClaimConfiguration(string schema)
        {
            ToTable("ResourceClaims", schema);
            HasKey(x => x.ResourceClaimId);

            Property(x => x.ResourceClaimId).HasColumnName(@"ResourceClaimId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.ResourceName).HasColumnName(@"ResourceName").HasColumnType("nvarchar").IsRequired().HasMaxLength(2048);
            Property(x => x.ClaimName).HasColumnName(@"ClaimName").HasColumnType("nvarchar").IsRequired().HasMaxLength(2048);
            Property(x => x.ParentResourceClaimId).HasColumnName(@"ParentResourceClaimId").HasColumnType("int").IsOptional();
            Property(x => x.ApplicationApplicationId).HasColumnName(@"Application_ApplicationId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasOptional(a => a.ParentResourceClaim).WithMany(b => b.ResourceClaims).HasForeignKey(c => c.ParentResourceClaimId).WillCascadeOnDelete(false); // FK_dbo.ResourceClaims_dbo.ResourceClaims_ParentResourceClaimId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
