// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // SecurityStrategies
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class SecurityStrategy
    {
        public int ResourceClaimId { get; set; } // ResourceClaimId (Primary key)
        public int ClaimsetId { get; set; } // ClaimsetId (Primary key)
        public string ResourceName { get; set; } // ResourceName (Primary key) (length: 2048)
        public string ClaimSetName { get; set; } // ClaimSetName (Primary key) (length: 255)
        public string ReadStrategy { get; set; } // ReadStrategy (length: 255)
        public string CreateStrategy { get; set; } // CreateStrategy (length: 255)
        public string UpdateStrategy { get; set; } // UpdateStrategy (length: 255)
        public string DeleteStrategy { get; set; } // DeleteStrategy (length: 255)

        public SecurityStrategy()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
