// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // SiteContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class SiteContent
    {
        public int Id { get; set; } // Id (Primary key)
        public int SiteContentTypeId { get; set; } // SiteContentTypeId
        public string Body { get; set; } // Body (length: 8000)

        // Foreign keys

        /// <summary>
        /// Parent Lookup pointed by [SiteContent].([SiteContentTypeId]) (FK_SiteContent_Type)
        /// </summary>
        public virtual Lookup Lookup { get; set; } // FK_SiteContent_Type

        public SiteContent()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
