// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // SubscriptionAction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class SubscriptionAction
    {
        public int SubscriptionActionId { get; set; } // SubscriptionActionId (Primary key)
        public string ActionName { get; set; } // ActionName (length: 32)

        // Reverse navigation

        /// <summary>
        /// Child Subscriptions where [Subscription].[SubscriptionActionId] point to this entity (FK_Subscription_SubscriptionAction)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Subscription> Subscriptions { get; set; } // Subscription.FK_Subscription_SubscriptionAction

        public SubscriptionAction()
        {
            Subscriptions = new System.Collections.Generic.List<Subscription>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
