// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // SubscriptionAction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class SubscriptionActionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SubscriptionAction>
    {
        public SubscriptionActionConfiguration()
            : this("dbo")
        {
        }

        public SubscriptionActionConfiguration(string schema)
        {
            ToTable("SubscriptionAction", schema);
            HasKey(x => x.SubscriptionActionId);

            Property(x => x.SubscriptionActionId).HasColumnName(@"SubscriptionActionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ActionName).HasColumnName(@"ActionName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
