// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class User
    {
        public int UserId { get; set; } // UserId (Primary key)
        public string Email { get; set; } // Email
        public string FullName { get; set; } // FullName
        public int? VendorVendorId { get; set; } // Vendor_VendorId

        // Reverse navigation

        /// <summary>
        /// Child ApiClients where [ApiClients].[User_UserId] point to this entity (FK_dbo.ApiClients_dbo.Users_User_UserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ApiClient> ApiClients { get; set; } // ApiClients.FK_dbo.ApiClients_dbo.Users_User_UserId
        /// <summary>
        /// Parent (One-to-One) User pointed by [UserAsmUser].[User_UserId] (FK_UserAsmUser_Users)
        /// </summary>
        public virtual UserAsmUser UserAsmUser { get; set; } // UserAsmUser.FK_UserAsmUser_Users

        // Foreign keys

        /// <summary>
        /// Parent Vendor pointed by [Users].([VendorVendorId]) (FK_dbo.Users_dbo.Vendors_Vendor_VendorId)
        /// </summary>
        public virtual Vendor Vendor { get; set; } // FK_dbo.Users_dbo.Vendors_Vendor_VendorId

        public User()
        {
            ApiClients = new System.Collections.Generic.List<ApiClient>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
