// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // VendorNamespacePrefixes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class VendorNamespacePrefix
    {
        public int VendorNamespacePrefixId { get; set; } // VendorNamespacePrefixId (Primary key)
        public string NamespacePrefix { get; set; } // NamespacePrefix (length: 255)
        public int VendorVendorId { get; set; } // Vendor_VendorId

        // Foreign keys

        /// <summary>
        /// Parent Vendor pointed by [VendorNamespacePrefixes].([VendorVendorId]) (FK_dbo.VendorNamespacePrefixes_dbo.Vendors_Vendor_VendorId)
        /// </summary>
        public virtual Vendor Vendor { get; set; } // FK_dbo.VendorNamespacePrefixes_dbo.Vendors_Vendor_VendorId

        public VendorNamespacePrefix()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
