// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ed_Fi.Credential.Domain.Model
{

    // VendorEmailDomains
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class VendorEmailDomain
    {
        public int VendorEmailDomainId { get; set; } // VendorEmailDomainId (Primary key)
        public string EmailDomain { get; set; } // EmailDomain (length: 255)
        public int VendorVendorId { get; set; } // Vendor_VendorId

        // Foreign keys

        /// <summary>
        /// Parent Vendor pointed by [VendorEmailDomains].([VendorVendorId]) (FK_dbo.VendorEmailDomains_dbo.Vendors_Vendor_VendorId)
        /// </summary>
        public virtual Vendor Vendor { get; set; } // FK_dbo.VendorEmailDomains_dbo.Vendors_Vendor_VendorId

        public VendorEmailDomain()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
